include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [ build/**, lib/**.freezed.dart ]

linter:
  rules:
    avoid_catches_without_on_clauses: false
    avoid_equals_and_hash_code_on_mutable_classes: false
    avoid_function_literals_in_foreach_calls: false
    avoid_field_initializers_in_const_classes: true
    avoid_print: true
    avoid_renaming_method_parameters: false
    avoid_returning_null: false
    constant_identifier_names: false
    curly_braces_in_flow_control_structures: true
    directives_ordering: true
    exhaustive_cases: true
    file_names: true
    flutter_style_todos: true
    implementation_imports: true
    library_names: true
    lines_longer_than_80_chars: false
    null_closures: false
    overridden_fields: false
    prefer_collection_literals: true
    prefer_function_declarations_over_variables: false
    prefer_relative_imports: false
    prefer_const_declarations: false
    prefer_const_constructors_in_immutables: false
    prefer_const_constructors: false
    prefer_single_quotes: true
    public_member_api_docs: false
    sort_child_properties_last: true
    sort_constructors_first: false
    type_annotate_public_apis: false
    unnecessary_statements: true
    unnecessary_constructor_name: true
    use_key_in_widget_constructors: false
